# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pnpm-app"
client_id = "aea65649b6ccc12e9c49e1ce04751508"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
